[build-system]
requires = ["setuptools>=70", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "discord-ws"
description = "A bare-bones asynchronous Python wrapper for the Discord Gateway API."
requires-python = ">=3.11"
authors = [{ name = "thegamecracks" }]
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "httpx>=0.25.0",
    "websockets>=11.0.3",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "License :: OSI Approved",
    "License :: OSI Approved :: MIT License",
    "Private :: Do Not Upload",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Topic :: Internet",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]

[project.urls]
Homepage = "https://github.com/thegamecracks/discord-ws"

[project.optional-dependencies]
docs = [
    "Sphinx>=7.2.6",
    "autoclasstoc>=1.6.0",
    "furo>=2023.9.10",
]
tests = [
    "pytest>=7.4.2",
    "pytest-asyncio>=0.21.1",
]

[tool.setuptools_scm]

[tool.coverage.run]
branch = true
source_pkgs = ["discord_ws"]
omit = ["src/discord_ws/__main__.py"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if (typing\\.)?TYPE_CHECKING:",
    "if __name__ == \"__main__\":",
    "\\s*\\.\\.\\.$",
    "raise NotImplementedError",
    "def __repr__",
]
include_namespace_packages = true
