name: Lint with Pyright

on:
  push:
    paths:
      - 'src/**.py'
      - 'tests/**.py'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        cache: pip
        cache-dependency-path: pyproject.toml
        python-version: '3.11'
    - run: pip install pyright
    - run: pip install .[tests]
    - run: pyright
