name: Run pytest

on:
  push:
    paths:
      - 'src/**.py'
      - 'tests/**.py'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**.py'
      - 'tests/**.py'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - uses: actions/setup-python@v5
      with:
        cache: pip
        cache-dependency-path: pyproject.toml
        python-version: '3.11'
    - run: pip install .[tests]
    - run: pytest
